name: "Prototype Groups"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: read
      actions: read
      issues: write
      pull-requests: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: Delete existing groups.yaml
        run: |
          echo "${{ toJson(github.event.workflow_run) }}"
          rm ./config/groups.yaml

      - name: Download PR artifact
        uses: actions/download-artifact@v4
        with:
          name: groups.yaml
          path: ./config/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Format groups.yaml
      #   run: |
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git add config/groups.yaml
      #     git commit -m 'Temporary commit'
      #     npm run format-config

      # - name: Check for changes
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     if [ ! -z "$(git status --porcelain)" ]; then
      #       echo \
      #         'Running \`npm run format-config\` changed the formatting of \`groups.yaml\`:\n\n\`\`\`diff\n' \
      #         "$(git diff)\n" \
      #         '\`\`\`\n\nPlease run \`npm run format-config\` locally and commit the changes.' | gh pr comment --body-file - ${{ github.event.workflow_run.pull_requests[0].number }}
      #     fi

      - name: Validate configuration
        run: npm run validate
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}

      - name: "Post changes as PR comment"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let markdown = 'changes.md';
            let issue_number = Number(fs.readFileSync('./config/pr.yaml', 'utf-8'));

            if (fs.existsSync(markdown)) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: fs.readFileSync('changes.md', 'utf-8')
              });
            }
